export default {
  baseUrl: 'http://65.0.17.153:3000/api/v1/',
  shops: 'getAllShops',
  products: 'product/getProducts',
  orders: 'getCheckoutDetails',
  login: 'user/validate',
  changeQuantity: 'product/changeQuantity',
  signUp: 'shop/signup',
  categories: 'getAllCategoriesAndBrands',
  addProduct: 'product/add',
  updateProduct: 'product/update',
  productImages: 'product/getPhotosLink',
  productAttributes: 'product/getProductAttrs',
  changeStatus: 'product/liveStatusChanged',
  approveProductsAdmin: 'product/statusChanged',
  approveShopsAdmin: 'shop/statusChanged',
  photoupload: 'photoupload',
  acceptOrDeclineOrder: 'checkout/statusChanged',
  sendOTP: 'sendOTP',
  verityOTP: 'verifyOTP',
};
